"""
Citation Manager Module for GraniteScholar Research Agent.
Generates APA, IEEE, Harvard, Chicago, and BibTeX citations and manages export libraries.
"""

from typing import List, Dict, Any, Optional

class CitationManager:
    """
    Formats academic citations across major standards and generates BibTeX files.
    """

    @staticmethod
    def format_citation(paper: Dict[str, Any], style: str = "APA") -> str:
        """
        Formats a single paper citation according to the specified citation style.
        """
        authors = paper.get("authors", ["Anonymous"])
        first_author = authors[0] if authors else "Anonymous"
        
        if len(authors) == 1:
            author_str_apa = first_author
            author_str_ieee = first_author
        elif len(authors) == 2:
            author_str_apa = f"{authors[0]} & {authors[1]}"
            author_str_ieee = f"{authors[0]} and {authors[1]}"
        else:
            author_str_apa = f"{first_author} et al."
            author_str_ieee = f"{first_author} et al."

        title = paper.get("title", "Untitled").rstrip(".")
        year = paper.get("year", "2024")
        venue = paper.get("venue", "Scientific Repository")
        url = paper.get("url", "")
        doi = paper.get("doi", "")

        style_upper = style.upper()

        if style_upper == "APA":
            doi_part = f" https://doi.org/{doi}" if doi else (f" {url}" if url else "")
            return f"{author_str_apa} ({year}). {title}. *{venue}*.{doi_part}"

        elif style_upper == "IEEE":
            return f'{author_str_ieee}, "{title}," *{venue}*, {year}. [Online]. Available: {url}'

        elif style_upper == "HARVARD":
            return f"{author_str_apa}, {year}. {title}. *{venue}*. Available at: <{url}> [Accessed 2026]."

        elif style_upper == "CHICAGO":
            return f'{author_str_apa}. "{title}." *{venue}* ({year}). {url}.'

        elif style_upper == "BIBTEX":
            return CitationManager.to_bibtex(paper)

        else: # Default APA
            return f"{author_str_apa} ({year}). {title}. *{venue}*."

    @staticmethod
    def to_bibtex(paper: Dict[str, Any]) -> str:
        """
        Converts a paper object into standard BibTeX entry format.
        """
        authors = paper.get("authors", ["Anonymous"])
        author_field = " and ".join(authors)
        title = paper.get("title", "Untitled")
        year = paper.get("year", 2024)
        venue = paper.get("venue", "arXiv")
        paper_id = paper.get("id", "ref1").replace(":", "_").replace(".", "_")

        return (
            f"@article{{{paper_id},\n"
            f"  author    = {{{author_field}}},\n"
            f"  title     = {{{{{title}}}}},\n"
            f"  journal   = {{{venue}}},\n"
            f"  year      = {{{year}}},\n"
            f"  url       = {{{paper.get('url', '')}}},\n"
            f"  doi       = {{{paper.get('doi', '')}}}\n"
            f"}}"
        )

    @staticmethod
    def generate_bibtex_library(papers: List[Dict[str, Any]]) -> str:
        """
        Generates a complete multi-entry BibTeX string for a collection of papers.
        """
        if not papers:
            return "% No papers selected for BibTeX export."
        
        entries = [CitationManager.to_bibtex(p) for p in papers]
        header = f"% Generated by GraniteScholar (IBM Granite Research Agent)\n% Total Entries: {len(papers)}\n\n"
        return header + "\n\n".join(entries)
